### ISSUE TITLE
Alimentación Mini docking hub USB-C HDMI

### ISSUE THREAD

**Issue by Llazcanoster** [Slimbook-Team/slimbook_service#13]
Buenos días,
Recientemente hemos comprado dos ProX15 con un Mini dock hub USB-C HDMI. En principio he leído que debería funcionar la alimentación a través del dock con un cargador USB-C superior a 65W, pero no me funciona ¿Hay alguna especificación más concreta para el cargador?
El modelo de que dispongo es un DL90200450 (Para Lenovo) que alcanza los 90W
También he probado con un SM65CL-02 (También para Lenovo) pero solo alcanza 65W

Saludos y gracias.

**Comment by slimbook** [comment]
Hola, puedes mandar esta consulta tal cual a info@slimbook.es, este tipo de consultas deben gestionarse por correo o a través del foro de slimbook, no en los repositorios de las apps. 
En el departamento de info encontrarán una solución ;)
Un saludo!
