### ISSUE TITLE
[Security] event-notify.py messages can be read from other computer

### ISSUE THREAD

**Issue by gvrubio** [Slimbook-Team/slimbook_service#17]
Doing an nmap scan of my slimbook I noticed port 8999 open.

I did ss -tulpn and saw that the port was binded by the event-notify.py slimbook service.

I did a quick and dirty zmq client using python:
```PYTHON
import zmq

# Define the address of the ZeroMQ server
server_address = "tcp://laptopIP:8999"  # Replace SERVER_IP_OR_HOSTNAME with the actual IP address or hostname

# Create a ZeroMQ context and socket for subscribing
context = zmq.Context()
socket = context.socket(zmq.SUB)

try:
    # Connect to the ZeroMQ server
    socket.connect(server_address)

    # Subscribe to all messages (empty string means all topics)
    socket.setsockopt_string(zmq.SUBSCRIBE, "")

    # Start listening for messages
    while True:
        message = socket.recv_string()
        print(f"Received message: {message}")

except zmq.ZMQError as e:
    print("Error:", e)

finally:
    # Close the socket and context when done
    socket.close()
    context.term()
```

and now, using that client, I'm able to read the silent mode and super key disable events from another computer.
Should that be how it works?

I did change the bind IP on the event-notify.py file to localhost, and it didn't worked, but using 127.0.01, worked just well, and the port is now not open to other computers on the network (Since the zmq server is not binded to the physical network cards)

This is a minor info leak, but maybe with more testing can be leveraged to something worst :(

cheers!

**Comment by Lt-Henry** [comment]
I am going to close this issue as it is already fixed on recent versions.
