### ISSUE TITLE
Option to disable trackpack by halves

### ISSUE THREAD

**Issue by piranna** [Slimbook-Team/slimbook_service#7]
On SLimbook Executive, default behavior of disable trackpad buttons are left button fully disable the trackpad, and right button only disable right half. Add an option so left button disable only the half side of the trackpad instead of fully doing it.

**Comment by slimbook** [comment]
I'm afraid this is not very feasible for now, as it only emits a signal once double click is performed, and it would require much work, maybe even a BIOS/EC update.

**Comment by piranna** [comment]
does the signal has info about what disable button is being double clicked? how is being disabled right half of the trackpad? where can I read info or the dataspec about it?

**Comment by slimbook** [comment]
The right half is disabled directly by hardware, the whole touchpad is handled [here](https://github.com/Slimbook-Team/slimbook_service/blob/5dc6b651ca3eb55431c7a50a4fc2f1e9726051e7/slimbook/usr/share/slimbook/event-notify.py#L207) by this application, triggered by a keyboard event. We use [ioctl](https://docs.python.org/3/library/fcntl.html)  [here](https://github.com/Slimbook-Team/slimbook_service/blob/5dc6b651ca3eb55431c7a50a4fc2f1e9726051e7/slimbook/usr/share/slimbook/event-notify.py#L224) to read the status and set it.

**Comment by piranna** [comment]
> The right half is disabled directly by hardware

I though it was done fully on software... my intention was just to allow to have enabled only right side :-(

**Comment by slimbook** [comment]
Yes, that is the thing, maybe some day ;) however, If I find something I'll tell you.

**Comment by piranna** [comment]
> however, If I find something I'll tell you.

Please and thank you :-)
