### ISSUE TITLE
Slimbook service keeps changing performance mode to "Silent" automatically

### ISSUE THREAD

**Issue by aliquo93** [Slimbook-Team/slimbook_service#9]
Hi, as the title says, I have this problem since the last update, I keep getting every 5-10 minutes this notification from Slimbook Service (see attached screenshot)... it's a known bug? Any fix or workaround? Thanks in advance.

This is happening on a Slimbook Titan on Kubuntu 22.04.

![1](https://user-images.githubusercontent.com/9071297/201788493-28fcea63-4a74-40ef-a696-eca47d389e72.png)

**Comment by aliquo93** [comment]
Also, how can I know (and set) the performance mode from the terminal?

**Comment by slimbook** [comment]
> Also, how can I know (and set) the performance mode from the terminal

That performance mode is set only from the button next to the power button, so you should be able to change it by clicking on it.
To check silent and turbo mode values:
`cat /sys/devices/platform/qc71_laptop/*_mode`
I've detected that the service could be reading this incorrectly, so I'm doing some tests to fix it.

**Comment by aliquo93** [comment]
> > Also, how can I know (and set) the performance mode from the terminal
> 
> That performance mode is set only from the button next to the power button, so you should be able to change it by clicking on it. To check silent and turbo mode values: `cat /sys/devices/platform/qc71_laptop/*_mode` I've detected that the service could be reading this incorrectly, so I'm doing some tests to fix it.

Even if I click that button, I don't get any notification from Slimbook Service, but it still inform me that the mode is set to "Silent" every 5 minutes.

**Comment by slimbook** [comment]
Hi, you can now test new [version 0.3.3 ](https://github.com/Slimbook-Team/slimbook_service/releases/tag/0.3.3).
If problem persists, please provide the output of :
`sudo systemctl status slimbook.service`

**Comment by aliquo93** [comment]
> Hi, you can now test new [version 0.3.3 ](https://github.com/Slimbook-Team/slimbook_service/releases/tag/0.3.3). If problem persists, please provide the output of : `sudo systemctl status slimbook.service`

Hi, thanks! I've just updated, I'll let you know in case of any problem.
